package com.payflowapi.repository;

import com.payflowapi.entity.Payslip;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface PayslipRepository extends JpaRepository<Payslip, Long> {

    // Find all payslips for an employee
    List<Payslip> findByEmployeeIdOrderByYearDescMonthDesc(Long employeeId);

    // Find payslip for specific month and year
    Optional<Payslip> findByEmployeeIdAndMonthAndYear(Long employeeId, String month, Integer year);

    // Find payslips by year
    List<Payslip> findByEmployeeIdAndYearOrderByMonthDesc(Long employeeId, Integer year);

    // Find payslips by month across all years
    List<Payslip> findByEmployeeIdAndMonthOrderByYearDesc(Long employeeId, String month);

    // Find all payslips for a specific year and month
    List<Payslip> findByMonthAndYearOrderByEmployeeIdAsc(String month, Integer year);

    // Find latest payslip for employee
    Optional<Payslip> findTopByEmployeeIdOrderByYearDescMonthDesc(Long employeeId);

    // Check if payslip exists for employee in specific month/year
    boolean existsByEmployeeIdAndMonthAndYear(Long employeeId, String month, Integer year);

    // Find payslips by status
    List<Payslip> findByStatusOrderByGeneratedOnDesc(String status);

    // Find payslips generated by specific user
    List<Payslip> findByGeneratedByOrderByGeneratedOnDesc(String generatedBy);

    // Custom query to get payslip summary
    @Query("SELECT p FROM Payslip p WHERE p.employeeId = :employeeId AND p.year >= :year ORDER BY p.year DESC, p.month DESC")
    List<Payslip> findRecentPayslips(@Param("employeeId") Long employeeId, @Param("year") Integer year);

    // Get all employees who have payslips
    @Query("SELECT DISTINCT p.employeeId FROM Payslip p ORDER BY p.employeeId")
    List<Long> findDistinctEmployeeIds();
}
